import React, { useEffect, useState } from 'react';
import {
  View,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Image,
  Animated,
} from 'react-native';
import Ionicons from 'react-native-vector-icons/Ionicons';
import { useNavigation } from '@react-navigation/native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { COLORS, FONTS, genericStyles } from '../../../constants';
import Label from '../../../components/Label/Labels';

const ConfirmAppointment = ({ route }: any) => {
  const navigation = useNavigation<any>();
  const doctor = route?.params?.doctor;
  const problem = route?.params?.problem;
  const request = route?.params?.request;

  const [scaleAnim] = useState(new Animated.Value(0));

  useEffect(() => {
    Animated.spring(scaleAnim, {
      toValue: 1,
      useNativeDriver: true,
      speed: 8,
    }).start();
  }, [scaleAnim]);

  if (!doctor) {
    return null;
  }

  return (
    <SafeAreaView style={[genericStyles.container, styles.safeContainer]}>
      <ScrollView style={styles.container} showsVerticalScrollIndicator={false}>
        <Animated.View
          style={[
            styles.successContainer,
            {
              transform: [{ scale: scaleAnim }],
            },
          ]}
        >
          <View style={styles.successCircle}>
            <Ionicons name="checkmark" size={60} color="#FFFFFF" />
          </View>
        </Animated.View>

        <View style={styles.messageContainer}>
          <Label
            labelContent="Request Submitted!"
            family={FONTS.AxiformaBold}
            textStyle={styles.congratsText}
          />
          <Label
            labelContent={`Your consultation request for ${doctor.name} has been sent successfully.`}
            family={FONTS.AxiformaRegular}
            textStyle={styles.messageText}
          />
        </View>

        <View style={styles.appointmentCard}>
          <View style={styles.appointmentHeader}>
            <Image source={{ uri: doctor.image }} style={styles.doctorImage} />
            <View style={styles.doctorInfo}>
              <Label
                labelContent={doctor.name}
                family={FONTS.AxiformaBold}
                textStyle={styles.doctorName}
              />
              <Label
                labelContent={doctor.specialty}
                family={FONTS.AxiformaRegular}
                textStyle={styles.specialty}
              />
              <View style={styles.clinicInfo}>
                <Ionicons name="location-outline" size={12} color="#718096" />
                <Label
                  labelContent={doctor.hospital}
                  family={FONTS.AxiformaRegular}
                  textStyle={styles.clinic}
                />
              </View>
            </View>
          </View>

          <View style={styles.appointmentDivider} />

          <View style={styles.detailsContainer}>
            <View style={styles.detailRow}>
              <View style={styles.detailIcon}>
                <Ionicons name="medical-outline" size={18} color={COLORS.primary} />
              </View>
              <View style={styles.detailContent}>
                <Label
                  labelContent="Problem"
                  family={FONTS.AxiformaRegular}
                  textStyle={styles.detailLabel}
                />
                <Label
                  labelContent={problem || 'Not shared'}
                  family={FONTS.AxiformaBold}
                  textStyle={styles.detailValue}
                />
              </View>
            </View>

            <View style={styles.detailRow}>
              <View style={styles.detailIcon}>
                <Ionicons name="document-text-outline" size={18} color={COLORS.primary} />
              </View>
              <View style={styles.detailContent}>
                <Label
                  labelContent="Request Id"
                  family={FONTS.AxiformaRegular}
                  textStyle={styles.detailLabel}
                />
                <Label
                  labelContent={request?._id || 'Generated by backend'}
                  family={FONTS.AxiformaBold}
                  textStyle={styles.detailValue}
                />
              </View>
            </View>

            <View style={styles.detailRow}>
              <View style={styles.detailIcon}>
                <Ionicons name="location-outline" size={18} color={COLORS.primary} />
              </View>
              <View style={styles.detailContent}>
                <Label
                  labelContent="Location"
                  family={FONTS.AxiformaRegular}
                  textStyle={styles.detailLabel}
                />
                <Label
                  labelContent={doctor.hospital}
                  family={FONTS.AxiformaBold}
                  textStyle={styles.detailValue}
                />
              </View>
            </View>
          </View>
        </View>

        <View style={styles.notesSection}>
          <View style={styles.notesHeader}>
            <Ionicons name="information-circle-outline" size={20} color={COLORS.primary} />
            <Label
              labelContent="Important"
              family={FONTS.AxiformaBold}
              textStyle={styles.notesTitle}
            />
          </View>
          <Label
            labelContent="Doctor will review your request from their dashboard. Keep your phone nearby for follow-up."
            family={FONTS.AxiformaRegular}
            textStyle={styles.notesText}
          />
        </View>

        <View style={styles.buttonsContainer}>
          <TouchableOpacity
            style={styles.editBtn}
            onPress={() => navigation.goBack()}
          >
            <Label
              labelContent="Edit Request"
              family={FONTS.AxiformaBold}
              textStyle={styles.editBtnText}
            />
          </TouchableOpacity>

          <TouchableOpacity
            style={styles.doneBtn}
            onPress={() =>
              navigation.navigate('MainTabs', {
                screen: 'Dashboard',
              })
            }
          >
            <Label
              labelContent="Done"
              family={FONTS.AxiformaBold}
              textStyle={styles.doneBtnText}
            />
          </TouchableOpacity>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
};

export default ConfirmAppointment;

const styles = StyleSheet.create({
  safeContainer: {
    backgroundColor: '#F8FAFB',
  },
  container: {
    flex: 1,
    backgroundColor: '#F8FAFB',
    paddingHorizontal: 14,
  },
  successContainer: {
    alignItems: 'center',
    marginTop: 30,
    marginBottom: 20,
  },
  successCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#26A69A',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#26A69A',
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    shadowOpacity: 0.3,
    elevation: 6,
  },
  messageContainer: {
    alignItems: 'center',
    marginBottom: 24,
  },
  congratsText: {
    fontSize: 22,
    color: COLORS.black,
    marginBottom: 12,
  },
  messageText: {
    fontSize: 14,
    color: '#4A5568',
    textAlign: 'center',
    lineHeight: 22,
  },
  appointmentCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    overflow: 'hidden',
    marginBottom: 20,
  },
  appointmentHeader: {
    flexDirection: 'row',
    padding: 16,
    alignItems: 'center',
  },
  doctorImage: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#E2E8F0',
  },
  doctorInfo: {
    marginLeft: 12,
    flex: 1,
  },
  doctorName: {
    fontSize: 16,
    color: COLORS.black,
  },
  specialty: {
    marginTop: 4,
    color: COLORS.primary,
    fontSize: 13,
  },
  clinicInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  clinic: {
    marginLeft: 6,
    color: '#64748B',
    fontSize: 12,
  },
  appointmentDivider: {
    height: 1,
    backgroundColor: '#E2E8F0',
  },
  detailsContainer: {
    padding: 16,
    gap: 14,
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  detailIcon: {
    width: 36,
    alignItems: 'center',
    marginTop: 2,
  },
  detailContent: {
    flex: 1,
  },
  detailLabel: {
    fontSize: 12,
    color: '#64748B',
  },
  detailValue: {
    marginTop: 4,
    fontSize: 14,
    color: COLORS.black,
  },
  notesSection: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
  },
  notesHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  notesTitle: {
    marginLeft: 8,
    fontSize: 16,
    color: COLORS.black,
  },
  notesText: {
    color: '#64748B',
    lineHeight: 20,
  },
  buttonsContainer: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 30,
  },
  editBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 14,
    alignItems: 'center',
    paddingVertical: 14,
    backgroundColor: '#FFFFFF',
  },
  editBtnText: {
    color: COLORS.black,
  },
  doneBtn: {
    flex: 1,
    borderRadius: 14,
    alignItems: 'center',
    paddingVertical: 14,
    backgroundColor: COLORS.primary,
  },
  doneBtnText: {
    color: '#FFFFFF',
  },
});
